### ISSUE TITLE
MacOS package improvements

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d-superbuild#173]
The version number should not appear in the app name:

<img width="600" alt="Screenshot 2024-04-24 at 14 43 45" src="https://github.com/f3d-app/f3d-superbuild/assets/6069752/a6e23a90-d808-4202-86b3-4074427489d0">

We need an installation background:

<img width="612" alt="Screenshot 2024-04-24 at 14 49 00" src="https://github.com/f3d-app/f3d-superbuild/assets/6069752/b7690711-93ae-4ca1-bbf8-623b82014f2b">
<img width="789" alt="Screenshot 2024-04-24 at 14 49 15" src="https://github.com/f3d-app/f3d-superbuild/assets/6069752/b0be45d4-afa1-4b94-a606-145e23a62dc2">

See https://gitlab.kitware.com/paraview/paraview-superbuild/-/tree/master/projects/apple/files?ref_type=heads

**Comment by mwestphal** [comment]
2. Seems pretty simple: https://gitlab.kitware.com/paraview/paraview-superbuild/-/merge_requests/501
